export const mockDoctors = [
  {
    id: 1,
    name: 'Dr. Sarah Johnson',
    specialty: 'Cardiology',
    qualification: 'MD, FACC',
    consultation_fee: 150,
    profile_image: null,
    is_available: true,
  },
  {
    id: 2,
    name: 'Dr. Michael Chen',
    specialty: 'Neurology',
    qualification: 'MD, PhD',
    consultation_fee: 200,
    profile_image: null,
    is_available: true,
  },
  {
    id: 3,
    name: 'Dr. Emily Williams',
    specialty: 'Pediatrics',
    qualification: 'MD, FAAP',
    consultation_fee: 120,
    profile_image: null,
    is_available: true,
  },
  {
    id: 4,
    name: 'Dr. James Brown',
    specialty: 'Orthopedics',
    qualification: 'MD, FAAOS',
    consultation_fee: 180,
    profile_image: null,
    is_available: true,
  },
  {
    id: 5,
    name: 'Dr. Lisa Anderson',
    specialty: 'Ophthalmology',
    qualification: 'MD, FACS',
    consultation_fee: 160,
    profile_image: null,
    is_available: true,
  },
];

export const mockServices = [
  { id: 1, name: 'General Consultation', description: 'Routine checkup and general health assessment', duration: 30, price: 80, is_active: true },
  { id: 2, name: 'Follow-up Visit', description: 'Follow-up consultation for ongoing treatment', duration: 15, price: 50, is_active: true },
  { id: 3, name: 'Specialist Consultation', description: 'Consultation with a specialist doctor', duration: 45, price: 150, is_active: true },
  { id: 4, name: 'Annual Health Check', description: 'Comprehensive annual health examination', duration: 60, price: 200, is_active: true },
  { id: 5, name: 'Lab Test', description: 'Laboratory tests and diagnostics', duration: 30, price: 100, is_active: true },
  { id: 6, name: 'Vaccination', description: 'Immunization and vaccination services', duration: 20, price: 60, is_active: true },
];

export const mockAppointments = [
  {
    id: 1,
    patient: { first_name: 'John', last_name: 'Doe', email: 'john@example.com' },
    doctor: mockDoctors[0],
    service: mockServices[0],
    date: new Date().toISOString().split('T')[0],
    start_time: '09:00',
    end_time: '09:30',
    status: 'confirmed',
    notes: '',
  },
  {
    id: 2,
    patient: { first_name: 'Jane', last_name: 'Smith', email: 'jane@example.com' },
    doctor: mockDoctors[1],
    service: mockServices[2],
    date: new Date().toISOString().split('T')[0],
    start_time: '10:00',
    end_time: '10:45',
    status: 'pending',
    notes: 'Headache concerns',
  },
  {
    id: 3,
    patient: { first_name: 'Bob', last_name: 'Wilson', email: 'bob@example.com' },
    doctor: mockDoctors[2],
    service: mockServices[0],
    date: new Date().toISOString().split('T')[0],
    start_time: '11:00',
    end_time: '11:30',
    status: 'completed',
    notes: '',
  },
];

export const mockStats = {
  total_patients: 150,
  total_doctors: 5,
  today_appointments: 12,
  pending_appointments: 4,
  completed_appointments: 8,
  weekly_appointments: [
    { date: '2024-01-15', count: 8 },
    { date: '2024-01-16', count: 12 },
    { date: '2024-01-17', count: 15 },
    { date: '2024-01-18', count: 10 },
    { date: '2024-01-19', count: 14 },
    { date: '2024-01-20', count: 6 },
    { date: '2024-01-21', count: 4 },
  ],
};
